language: csharp
dotnet: 3.1.101
dist: trusty

branches:
  only:
    - /.*/
    
before_install:
  - echo Action $TRAVIS_EVENT_TYPE triggered build by $TRAVIS_COMMIT commit.

jobs:
  include:
    - stage: "Build & Test"
      name: "Build & Test"
      script:
        - dotnet build -c Release --no-cache ./src/MockQueryable/MockQueryable.sln
        - dotnet test -c Release --no-build ./MockQueryable.Sample/MockQueryable.Sample.csproj

    - stage: "Code Coverage"
      name: "Code Coverage"
      install: dotnet tool install --global Codecov.Tool
      script:
        - dotnet test /p:CollectCoverage=true /p:CoverletOutput="../" /p:MergeWith="../coverage.json" /maxcpucount:1 /p:CoverletOutputFormat=\"json,opencover\"
        - $HOME/.dotnet/tools/codecov -f ./test/coverage.opencover.xml -t $CODECOV_TOKEN --flag unittests
